CREATE SEQUENCE SEQ_HIST_RECI
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE T_HIST_RECICLAGEM (
    ID_RECICLAGEM NUMBER DEFAULT SEQ_HIST_RECI.NEXTVAL NOT NULL,
    COD_USUARIO NUMBER(7) NOT NULL,
    DES_LOCAL VARCHAR2(60) NOT NULL,
    DAT_RECICLAGEM DATE NOT NULL,
    QTD_PESO FLOAT(6) NOT NULL
);
